FROM node:10

WORKDIR /usr/src/app
COPY ./package.json ./
COPY yarn.lock ./
RUN yarn install --modules-folder ../node_modules/
RUN yarn global add nodemon
COPY ./src ./src
COPY  /opt/environment/onem-zone/*.pem /opt/environment/onem-zone/
CMD [ "npm", "run", "start:docker" ]
